# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SwitchControllerWindow(object):
    def setupUi(self, SwitchControllerWindow):
        SwitchControllerWindow.setObjectName("SwitchControllerWindow")
        SwitchControllerWindow.resize(282, 181)
        icon = QtGui.QIcon.fromTheme("favicon")
        SwitchControllerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SwitchControllerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.num_outputs = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_outputs.setFont(font)
        self.num_outputs.setToolTip("")
        self.num_outputs.setObjectName("num_outputs")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.num_outputs.addItem("")
        self.gridLayout.addWidget(self.num_outputs, 0, 1, 1, 1)
        self.switch_test_time = QtWidgets.QSpinBox(self.centralwidget)
        self.switch_test_time.setMinimum(1)
        self.switch_test_time.setMaximum(255)
        self.switch_test_time.setProperty("value", 5)
        self.switch_test_time.setObjectName("switch_test_time")
        self.gridLayout.addWidget(self.switch_test_time, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.program_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.program_button.setFont(font)
        self.program_button.setObjectName("program_button")
        self.gridLayout.addWidget(self.program_button, 6, 4, 1, 1)
        self.pull_up_time = QtWidgets.QSpinBox(self.centralwidget)
        self.pull_up_time.setMinimum(1)
        self.pull_up_time.setMaximum(255)
        self.pull_up_time.setProperty("value", 20)
        self.pull_up_time.setObjectName("pull_up_time")
        self.gridLayout.addWidget(self.pull_up_time, 5, 1, 1, 1)
        self.pulse_width = QtWidgets.QSpinBox(self.centralwidget)
        self.pulse_width.setMinimum(1)
        self.pulse_width.setMaximum(255)
        self.pulse_width.setProperty("value", 1)
        self.pulse_width.setObjectName("pulse_width")
        self.gridLayout.addWidget(self.pulse_width, 3, 1, 1, 1)
        self.max_on_time = QtWidgets.QSpinBox(self.centralwidget)
        self.max_on_time.setMinimum(1)
        self.max_on_time.setMaximum(255)
        self.max_on_time.setProperty("value", 100)
        self.max_on_time.setObjectName("max_on_time")
        self.gridLayout.addWidget(self.max_on_time, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 4, 1, 1)
        self.output_mode = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_mode.setFont(font)
        self.output_mode.setToolTip("")
        self.output_mode.setObjectName("output_mode")
        self.output_mode.addItem("")
        self.output_mode.addItem("")
        self.output_mode.addItem("")
        self.gridLayout.addWidget(self.output_mode, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        SwitchControllerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SwitchControllerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 18))
        self.menubar.setObjectName("menubar")
        SwitchControllerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SwitchControllerWindow)
        self.statusbar.setObjectName("statusbar")
        SwitchControllerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SwitchControllerWindow)
        self.program_button.clicked.connect(SwitchControllerWindow.program_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(SwitchControllerWindow)

    def retranslateUi(self, SwitchControllerWindow):
        _translate = QtCore.QCoreApplication.translate
        SwitchControllerWindow.setWindowTitle(_translate("SwitchControllerWindow", "Switch Controller Programmer"))
        self.label_6.setText(_translate("SwitchControllerWindow", "Switch Test Time:"))
        self.label.setText(_translate("SwitchControllerWindow", "Output Mode:"))
        self.label_11.setToolTip(_translate("SwitchControllerWindow", "The number of switches you want to control."))
        self.label_11.setText(_translate("SwitchControllerWindow", "?"))
        self.num_outputs.setItemText(0, _translate("SwitchControllerWindow", "1"))
        self.num_outputs.setItemText(1, _translate("SwitchControllerWindow", "2"))
        self.num_outputs.setItemText(2, _translate("SwitchControllerWindow", "3"))
        self.num_outputs.setItemText(3, _translate("SwitchControllerWindow", "4"))
        self.num_outputs.setItemText(4, _translate("SwitchControllerWindow", "5"))
        self.num_outputs.setItemText(5, _translate("SwitchControllerWindow", "6"))
        self.num_outputs.setItemText(6, _translate("SwitchControllerWindow", "7"))
        self.num_outputs.setItemText(7, _translate("SwitchControllerWindow", "8"))
        self.label_5.setText(_translate("SwitchControllerWindow", "Resistor Pull Up Time:"))
        self.label_3.setText(_translate("SwitchControllerWindow", "Pulse Width:"))
        self.label_4.setText(_translate("SwitchControllerWindow", "Max On Time:"))
        self.label_8.setToolTip(_translate("SwitchControllerWindow", "The number of switches you want to control."))
        self.label_8.setText(_translate("SwitchControllerWindow", "?"))
        self.program_button.setText(_translate("SwitchControllerWindow", "Program Circuit"))
        self.label_12.setToolTip(_translate("SwitchControllerWindow", "The number of switches you want to control."))
        self.label_12.setText(_translate("SwitchControllerWindow", "?"))
        self.label_9.setToolTip(_translate("SwitchControllerWindow", "The number of switches you want to control."))
        self.label_9.setText(_translate("SwitchControllerWindow", "?"))
        self.label_10.setToolTip(_translate("SwitchControllerWindow", "To save the batteries, the maximum time an output can remain on can\n"
"be configured in increments of ~100 milliseconds"))
        self.label_10.setText(_translate("SwitchControllerWindow", "?"))
        self.pushButton.setText(_translate("SwitchControllerWindow", "Restore Defaults"))
        self.output_mode.setItemText(0, _translate("SwitchControllerWindow", "One Shot"))
        self.output_mode.setItemText(1, _translate("SwitchControllerWindow", "On/Off"))
        self.output_mode.setItemText(2, _translate("SwitchControllerWindow", "Retriggerable"))
        self.label_2.setText(_translate("SwitchControllerWindow", "Number of Outputs:"))
        self.label_7.setToolTip(_translate("SwitchControllerWindow", "The number of switches you want to control."))
        self.label_7.setText(_translate("SwitchControllerWindow", "?"))
